### ISSUE TITLE
Allow a Gravatar Alternative for profile images 

### ISSUE THREAD

**Issue by HalosGhost** [jcs/lobsters#232]
Due to an unfortunate circumstance, I have lost the information to recover my wordpress account, and as a result I cannot get access to the associated gravatar account.

Ideally, I would love it if lobste.rs allowed me to just upload an image to serve as my profile picture; but in lieu of that (knowing that such a feature can lead to a significant increase in storage use on the server), the ability to specify an arbitrary URL for my profile image would be deeply appreciated. Is this something that you would be interested in adding?

**Comment by jcs** [comment]
I would rather not because it would need to store images or URLs for multiple size icons and this seems like a very small edge case.

If your e-mail system allows aliases (like user+lobsters@example.com), you can just register a new Gravatar account with that and set that as your Lobsters account email address.

**Comment by HalosGhost** [comment]
@jcs, actually, I have a new email to use; but my old username cannot be recovered. ):

However, I completely understand your predicament and don't blame you at all. Keep up the good work!
