### ISSUE TITLE
Merging a newer popular story into an older one should not remove the story from the front page

### ISSUE THREAD

**Issue by cnst** [jcs/lobsters#300]
It happens quite often that several links to the same story get posted, and sometimes they have vastly different popularity ratings.

Currently, if a new popular story is merged into an older and/or less popular one, then the whole new discussion will assume the less popular score, and may disappear from the front page.

This seems wrong -- when merging, the new discussion should always be scored at either an intersection of the two stories (e.g., sum of all votes, minus the duplicates), or at the very least at the most popular one.

A good example: a link to a reddit discussion was posted about two weeks ago, but didn't get traction, perhaps due to a less-than-ideal title.  https://lobste.rs/s/gdinst/finally_fired_after_6_years_r.  Then today a link to some specialised site was posted, which basically just copy-pasted the main post from the reddit discussion as above, without really adding anything new, other than a lot of very spammy and obnoxious ads, an irrelevant stock photo, and a couple of extra line breaks.  https://lobste.rs/s/dbpomt/programmer_fired_after_6_years_realizes  As the new link was highly voted and had a lot of discussion, the moderator decided to merge the better link into the worse one, to make sure it wouldn't disappear from the front page.  That seems like a shortcoming of the engine.

**Comment by IreneKnapp** [comment]
I'd like to comment, as the mod in question, that it's behavior I think I've observed, but merges don't happen frequently enough for me to be sure of the cause, and it never seemed worth reading the code over.

I do think that, if the behavior is as described, the engine should probably change to use the newer of the two timestamps for ranking purposes, whichever it is.

**Comment by someplaceguy** [comment]
This still seems to be happening. Just now, the [On community in Nix](https://determinate.systems/posts/on-community-in-nix/) story got merged with the [Open letter to the NixOS foundation](https://save-nix-together.org/) story and then immediately disappeared from the front page.

I've observed this with other stories as well.

**Comment by pushcx** [comment]
This behavior was reverted in c602b0196523f96e2da757462094fd0d80a8d669 and hasn't been discussed since (the Jan 7 2022 commit 7e26e8a linked above is an echo of 2b278d1 from a branch or rebase or something). I don't have a strong feeling on changing this behavior, but it's part of why I created [/active](https://lobste.rs/active)... and neither nix story appears there, so I'll file a bug.

After the "On community in nix" response (/s/pntava) was merged into the primary (/s/0qvtim) it shouldn't appear separately on any page of the home or /newest, though the data model makes bugs pretty easy to reinsert.

**Comment by someplaceguy** [comment]
> I don't have a strong feeling on changing this behavior, but it's part of why I created [/active](https://lobste.rs/active)

I've been reading lobste.rs for years and yet I had never realized /active even existed, so I'm not sure this is ideal.

The commit reverting the fix for this issue doesn't explain why the behavior is confusing. If the reason for the confusion is that the merge was apparently resurrecting the older thread(s), might I suggest that in addition to using the newer `created_at` date for the purposes of calculating hotness, that the front page would show the title of the *newest* story rather than the *oldest* one (or most upvoted one), like it seems to do now?

I think this would be far preferred to the current state, where newer stories seem to completely disappear from view due to the merges even though they might add really interesting new viewpoints to an ongoing discussion.

**Comment by pushcx** [comment]
I put `/active` next to the logo to make it obvious. I don't see a way to further highlight it without doing something obnoxious like adding a color or animation. Maybe add a microcopy to the bottom of page 2/3 of the front page to call it out? Any ideas for what might have been helpful to you?

I think showing the title of the newest story in a merge would be pretty confusing. Commenters look for stories to see new comments, and a lot of the replies (especially the hot takes) have much less clear titles.

**Comment by someplaceguy** [comment]
> I put /active next to the logo to make it obvious. 

Yes, it is quite obvious (especially now that I've looked for it) and I can't explain why I didn't see it before. Actually, I suspect I did see it before, I just never had a need to use it, so I kind of forgot about it. Perhaps the "Active" name is not entirely clear or seemingly useful, in fact to me it kind of suggests that it's the same thing as the front page (since those are the hottest and therefore presumably most active stories), but I admit this might be a *me* problem.

In contrast, I was quite aware of the "Recent", "Search" and "Submit" pages, since I've used them quite often before (well, I've only used "Submit" once but it's obvious such feature needs to exist). The "Comments" page was similarly forgotten because I almost never use it (except once or twice when I was really bored, I think).

In summary, I don't really have good suggestions, sorry! I wish I could help, but I can't come up with a better name and I'm really incompetent at UX and web design.

> I think showing the title of the newest story in a merge would be pretty confusing.

That's unfortunate. From my perspective, in that case it kind of seems like the merge feature is detrimental to the site rather than being useful, especially when the main story has already fallen from the front page. In practice, it's akin to hiding newer stories about a previously-discussed topic. Also, when the number of comments gets high in the older stories, it seem to prevent discussion about the newer stories on their own merits separately from the previous ones, since you'd have to wade through a lot of upvoted-comments to get to the newer ones (sometimes more than a hundred, in fact).

That said, I understand that this is just my own subjective opinion and that there might also be benefits to the merge feature that I'm not necessarily seeing (perhaps it might be especially useful when many similar stories about the same issue get submitted at the same time?).

Thanks!

**Comment by someplaceguy** [comment]
Sorry, just another minor point: I've also observed that merged stories (such as the Nix ones I mentioned) contain stories that are responses to the previous ones, and this can result in situations where it's difficult (or in extreme cases, even impossible) to discern whether a comment was in response to one of the stories or the other. This can be quite confusing.

A possible solution (besides not merging such stories) might be to somehow allow the user to select to which story the comment applies to, and then somehow show this for each comment (although again, UX is not my strong suit, so I'm not sure if this would be too distracting). Just something to think about.

Thanks!

**Comment by pushcx** [comment]
Yeah. If the comments were posted before the story were merged they show the title, but there's no way to attach a comment once the merge has happened. UI that supports this probably also implies the data model fixes in #519.
