### ISSUE TITLE
Prevent name squatting when changing names.

### ISSUE THREAD

**Issue by angersock** [jcs/lobsters#369]
It is currently possible for users to change their display names, which is great.

This name change also means that the login username changes, which is less great but okay.

However, *once a user changes their name* that username becomes available for reregistering.

A malicious actor could take over an old username and do annoying things with it.

So, perhaps we should track a few of a user's previous names, and not allow reregistering of those names without a confiramtion or whatever.

**Comment by jcs** [comment]
how does that prevent squatting?  reserving more than the user's current username would just make squatting even more possible because you can change it a few times and lock out usernames.

also, not reserving the previous username is pretty much how every other site works (that allows changing a username) like twitter, github, etc.
