### ISSUE TITLE
Avatar not updating

### ISSUE THREAD

**Issue by zg** [jcs/lobsters#392]
I updated my avatar via Gravatar about a week ago, but I am still seeing my old avatar on Lobste.rs. Looks like the avatar caching mechanism doesn't have an expiration. Is this intentional?

**Comment by jcs** [comment]
It has a server-side expiration, but it can take up to a week to delete cached avatars (it does them randomly so that a big group aren't all re-fetched at once).

**Comment by zg** [comment]
Why was a caching mechanism enforced?

**Comment by pushcx** [comment]
Presumably Gravatar, a free service available to any third-party website, does this to keep down their bandwith costs.

**Comment by jcs** [comment]
It was added for a few reasons:

- Gravatar still uses md5 for hashing e-mail addresses.  Not a huge deal, but at least now e-mail addresses are completely hidden from users.
- lobste.rs enabled http2 a while back, and performance is improved by loading lots of tiny icons through http2 instead of all the calls to gravatar's http1 server.
- It allows for some other mechanism of avatars in the future, such as uploading directly to the site or showing a custom avatar for certain events.

I would not be opposed to a PR to add functionality to manually expire the cached avatar from the settings page either automatically (it's cheap) or from a link.

**Comment by jcs** [comment]
There's a manual expiry function in the settings now.

https://github.com/jcs/lobsters/commit/d42685f4e20f1ba77f4eb09f83a7a7dca7c588e1
